import { keyBy } from 'lodash-es';
import { GetSmartDeviceModelDpSchema } from '@ray-js/panel-sdk';

// Auto-generated by TuyaOpen IDE — do not edit manually.
// Regenerate via the MiniApp panel's "Sync DPs from Cloud" action.
export const lampSchema = [] as const;

export const lampSchemaMap = keyBy(lampSchema, 'code') as GetSmartDeviceModelDpSchema<typeof lampSchema>;
